server:
  port: 9000


spring:
  application:
    name: proxy-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:9090
              predicates:
                - Path=/api/users/**,/api/profiles/**

            - id: token-verification
              uri: no://op
              predicates:
                - Path=/api/auth/me/**
